export const ALL_SKILLS = [
  'UI/UX Design',
  'Figma',
  'Ilustrasi',
  'Fotografi',
  'Video Editing',
  'Motion Design',
  'React',
  'Next.js',
  'Vue.js',
  'Node.js',
  'Python',
  'Machine Learning',
  'Data Analysis',
  'Flutter',
  'Swift',
  'Kotlin',
  'Laravel',
  'Django',
  'Statistik',
  'Matematika',
  'Penulisan',
  'Riset',
  'Presentasi',
  'Social Media',
  'Copywriting',
  'SEO',
  'Branding',
] as const;

export type Skill = (typeof ALL_SKILLS)[number];
